/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreatePollRouteImport } from './routes/create-poll'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotesPollIdRouteImport } from './routes/votes-poll/$id'

const CreatePollRoute = CreatePollRouteImport.update({
  id: '/create-poll',
  path: '/create-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesPollIdRoute = VotesPollIdRouteImport.update({
  id: '/votes-poll/$id',
  path: '/votes-poll/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-poll': typeof CreatePollRoute
  '/votes-poll/$id': typeof VotesPollIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-poll': typeof CreatePollRoute
  '/votes-poll/$id': typeof VotesPollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-poll': typeof CreatePollRoute
  '/votes-poll/$id': typeof VotesPollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-poll' | '/votes-poll/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-poll' | '/votes-poll/$id'
  id: '__root__' | '/' | '/create-poll' | '/votes-poll/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePollRoute: typeof CreatePollRoute
  VotesPollIdRoute: typeof VotesPollIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-poll': {
      id: '/create-poll'
      path: '/create-poll'
      fullPath: '/create-poll'
      preLoaderRoute: typeof CreatePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes-poll/$id': {
      id: '/votes-poll/$id'
      path: '/votes-poll/$id'
      fullPath: '/votes-poll/$id'
      preLoaderRoute: typeof VotesPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePollRoute: CreatePollRoute,
  VotesPollIdRoute: VotesPollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
